#!/bin/sh

. /lib/functions.sh
include /lib/network

config_load rygel

local l2dev iface
config_get l2dev "general" interface
iface=$(find_config ${l2dev})

[ -n "${iface}" -a ${INTERFACE} = ${iface} ] || return 0

case "$ACTION" in
	ifup)
		/etc/init.d/rygel restart
	;;
	ifdown)
		/etc/init.d/rygel stop
	;;
esac
